# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Notes"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://nareshganesan.github.io/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Naresh Ganesan"
  homepage = "http://nareshganesan.github.io/"

# If porting an existing theme
[original]
  name = "Naresh Ganesan"
  homepage = "http://nareshganesan.github.io/"
  repo = "https://github.com/nareshganesan/nareshganesan.github.io"
